In [ ]:
from bs4 import BeautifulSoup

from urllib import request
from urllib.request import urlopen
from urllib.parse import urlencode, quote_plus
from urllib.parse import unquote

from datetime import datetime
from datetime import timedelta
import datetime
from datetime import date

## 공휴일 날짜 API 수집

In [22]:
locdatel=[]
seql=[]
dateKindl=[]
isHolidayl=[]
dateNamel=[]
y=[]

In [23]:
for year in ['2015','2016','2017','2018','2019']:
    # ServiceKey(인증키)는 개별 요청 필요
    queryParams = urlencode({ quote_plus('ServiceKey') : '(인증키)',quote_plus('solYear') :year ,quote_plus('numOfRows') : '100'})
    open_url='http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getHoliDeInfo?'+queryParams

    res=requests.get(open_url)
    soup=BeautifulSoup(res.content,'html.parser')

    data=soup.find_all('item')
    for item in data:
        locdatel.append(item.find('locdate').text)
        seql.append(item.find('seq').text)
        isHolidayl.append(item.find('isholiday').text)
        dateNamel.append(item.find('datename').text)
        y.append(year)

In [24]:
holi=pd.DataFrame()
holi['locdate']=locdatel
holi['seq']=seql
holi['isHoliday']=isHolidayl
holi['dateName']=dateNamel
holi['year']=y

In [25]:
holi[holi.year=='2019']

     locdate seq isHoliday dateName  year
74  20190101   1         Y     1월1일  2019
75  20190204   1         Y       설날  2019
76  20190205   1         Y       설날  2019
77  20190206   1         Y       설날  2019
78  20190301   1         Y      삼일절  2019
79  20190505   1         Y     어린이날  2019
80  20190506   1         Y    대체공휴일  2019
81  20190512   1         Y   부처님오신날  2019
82  20190606   1         Y      현충일  2019
83  20190717   1         N      제헌절  2019
84  20190815   1         Y      광복절  2019
85  20190912   1         Y       추석  2019
86  20190913   1         Y       추석  2019
87  20190914   1         Y       추석  2019
88  20191003   1         Y      개천절  2019
89  20191009   1         Y      한글날  2019
90  20191225   1         Y    기독탄신일  2019

In [27]:
t=['월','화','수','목','금','토','일']

In [28]:
holi['week']=holi['locdate'].apply(lambda x: t[datetime.datetime.strptime(x,'%Y%m%d').weekday()])

In [29]:
holi[holi['year']=='2019']

     locdate seq isHoliday dateName  year week
74  20190101   1         Y     1월1일  2019    화
75  20190204   1         Y       설날  2019    월
76  20190205   1         Y       설날  2019    화
77  20190206   1         Y       설날  2019    수
78  20190301   1         Y      삼일절  2019    금
79  20190505   1         Y     어린이날  2019    일
80  20190506   1         Y    대체공휴일  2019    월
81  20190512   1         Y   부처님오신날  2019    일
82  20190606   1         Y      현충일  2019    목
83  20190717   1         N      제헌절  2019    수
84  20190815   1         Y      광복절  2019    목
85  20190912   1         Y       추석  2019    목
86  20190913   1         Y       추석  2019    금
87  20190914   1         Y       추석  2019    토
88  20191003   1         Y      개천절  2019    목
89  20191009   1         Y      한글날  2019    수
90  20191225   1         Y    기독탄신일  2019    수

In [30]:
holi.head(10)

    locdate seq isHoliday dateName  year week
0  20150101   1         Y       신정  2015    목
1  20150218   1         Y       설날  2015    수
2  20150219   1         Y       설날  2015    목
3  20150220   1         Y       설날  2015    금
4  20150301   1         Y      삼일절  2015    일
5  20150505   1         Y     어린이날  2015    화
6  20150525   1         Y    석가탄신일  2015    월
7  20150606   1         Y      현충일  2015    토
8  20150717   1         N      제헌절  2015    금
9  20150815   1         Y      광복절  2015    토

In [31]:
holi.to_csv("holi.csv",index=False,encoding="euc-kr")